#!/usr/bin/env bash
# transfers a file from a client to a server

# check if all parameters are provided
if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# assign parameter values to variables
FILE=$1
IP=$2
USERNAME=$3
SSH_KEY=$4

# transfer the file using scp
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE" "$USERNAME@$IP:~"

# check if the transfer was successful
if [ $? -eq 0 ]; then
    echo "File transfer successful!"
else
    echo "File transfer failed."
fi

