#!/usr/bin/env bash

# Install Nginx web server
sudo apt-get update
sudo apt-get install nginx -y

# Create a new configuration file for the custom 404 page
sudo sh -c 'echo "server {
  listen 80;
  server_name puppr;
  error_page 404 /4.tech04.html;
  location = /404.html {
     internal;
     root /var/www/html;
     echo \"Ceci n'est pas une page";
  }
}" > /etc/nginx/sites-available/custom404.conf'

# Create a symbolic link to the configuration file in the sites-enabled directory
sudo ln -s /etc/nginx/sites-available/custom404.conf /etc/nginx/sites-enabled/

# Test the configuration file for syntax errors
sudo nginx -t

# Restart Nginx to apply the new configuration
sudo systemctl restart nginx

