#!/usr/bin/env bash

# Install Nginx if it is not already installed
if [ ! -x "$(command -v nginx)" ]; then
  sudo apt-get update
  sudo apt-get install -y nginx
fi

# Add custom HTTP response header to Nginx
sudo sed -i '/http {/a \        server_tokens off;\n        add_header X-Served-By $hostname;' /etc/nginx/nginx.conf

# Test the Nginx configuration for syntax errors
sudo nginx -t

# If there are no syntax errors, restart the Nginx server to apply the changes
sudo systemctl restart nginx
